# Generated by Django 5.1.1 on 2024-10-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
    ]